experiment_name: "LLM_BART_Experiment"
min_pumps: 1
max_pumps: 20
reward_per_pump: 0.10
num_balloons: 5

# We'll remove the 'model' line from here so we can pass them in code instead.
# openrouter_api_key: "YOUR-OPENROUTER-KEY" 
# Optionally keep or remove. You can also set it in code or environment.
